from pathlib import Path
import json

from docx import Document

from app.core.config import Settings
from app.llm.docx_codegen import DocxCodegenResult
from app.renderers.codegen_docx_renderer import CodegenDocxRenderer
from app.renderers.docx_renderer import DocxRenderer
from app.schemas.document_spec import DocumentSpec
from app.services.docx_sandbox import SandboxResult


class FakeGenerator:
    def generate(self, document_spec: DocumentSpec) -> DocxCodegenResult:
        return DocxCodegenResult(
            python_code="print('generate docx')",
            warnings=["Codegen warning."],
            raw_output='{"python_code":"print()"}',
        )


class FailingGenerator:
    def generate(self, document_spec: DocumentSpec) -> DocxCodegenResult:
        raise RuntimeError("model unavailable")


class FakeSandbox:
    def run(self, *, input_dir: Path, output_dir: Path, code_filename: str) -> SandboxResult:
        assert (input_dir / "document_spec.json").exists()
        assert (input_dir / code_filename).exists()
        payload = json.loads((input_dir / "document_spec.json").read_text(encoding="utf-8"))
        assert payload["document_spec"]["schema_version"] == "document_spec.v1"

        document = Document()
        document.add_heading("Generated by sandbox", level=1)
        output_path = output_dir / "result.docx"
        document.save(output_path)
        return SandboxResult(
            exit_code=0,
            stdout="ok",
            stderr="",
            timed_out=False,
            output_path=output_path,
        )


def test_codegen_docx_renderer_uses_sandbox_result(tmp_path) -> None:
    renderer = CodegenDocxRenderer(
        Settings(artifact_storage_path=tmp_path),
        generator=FakeGenerator(),
        sandbox=FakeSandbox(),
    )

    rendered = renderer.render(
        "art_123",
        DocumentSpec(title="Spec", content_markdown="# Spec"),
    )

    document = Document(rendered.file_path)

    assert rendered.file_name == "art_123.docx"
    assert "Generated by sandbox" in [paragraph.text for paragraph in document.paragraphs]
    assert rendered.warnings == ["Codegen warning."]
    assert (tmp_path / "codegen" / "art_123" / "input" / "generated_code.py").exists()
    assert (tmp_path / "codegen" / "art_123" / "stdout.txt").read_text(encoding="utf-8") == "ok"


def test_codegen_docx_renderer_falls_back_when_codegen_fails(tmp_path) -> None:
    renderer = CodegenDocxRenderer(
        Settings(artifact_storage_path=tmp_path),
        generator=FailingGenerator(),
        sandbox=FakeSandbox(),
        fallback_renderer=DocxRenderer(Settings(artifact_storage_path=tmp_path)),
    )

    rendered = renderer.render(
        "art_123",
        DocumentSpec(title="Fallback", content_markdown="# Fallback\n\nBody"),
    )

    document = Document(rendered.file_path)
    paragraphs = [paragraph.text for paragraph in document.paragraphs]

    assert "Fallback" in paragraphs
    assert any("fallback renderer was used" in warning for warning in rendered.warnings)
