from pathlib import Path
import json

from docx import Document

from app.core.config import Settings
from app.llm.docx_codegen import DocxCodegenResult
from app.renderers.codegen_docx_renderer import CodegenDocxRenderer
from app.renderers.docx_renderer import DocxRenderer
from app.schemas.document_spec import DocumentSpec
from app.services.docx_sandbox import SandboxResult


class FakeGenerator:
    def generate(self, document_spec: DocumentSpec) -> DocxCodegenResult:
        return DocxCodegenResult(
            python_code="print('generate docx')",
            warnings=["Codegen warning."],
            raw_output='{"python_code":"print()"}',
        )


class FailingGenerator:
    def generate(self, document_spec: DocumentSpec) -> DocxCodegenResult:
        raise RuntimeError("model unavailable")


class RepairingGenerator:
    def __init__(self) -> None:
        self.repairs: list[dict] = []

    def generate(self, document_spec: DocumentSpec) -> DocxCodegenResult:
        return DocxCodegenResult(
            python_code="raise RuntimeError('broken')",
            warnings=[],
            raw_output='{"python_code":"broken"}',
        )

    def repair(
        self,
        *,
        document_spec: DocumentSpec,
        previous_python_code: str,
        sandbox_result: dict | None = None,
        validation_errors: list[str] | None = None,
    ) -> DocxCodegenResult:
        self.repairs.append(
            {
                "previous_python_code": previous_python_code,
                "sandbox_result": sandbox_result or {},
                "validation_errors": validation_errors or [],
            }
        )
        return DocxCodegenResult(
            python_code="print('fixed')",
            warnings=["Repair warning."],
            raw_output='{"python_code":"fixed"}',
        )


class FakeSandbox:
    def run(self, *, input_dir: Path, output_dir: Path, code_filename: str) -> SandboxResult:
        assert (input_dir / "document_spec.json").exists()
        assert (input_dir / code_filename).exists()
        payload = json.loads((input_dir / "document_spec.json").read_text(encoding="utf-8"))
        assert payload["document_spec"]["schema_version"] == "document_spec.v1"

        document = Document()
        document.add_heading(payload["document_spec"]["title"], level=1)
        document.add_paragraph("Generated by sandbox")
        output_path = output_dir / "result.docx"
        document.save(output_path)
        return SandboxResult(
            exit_code=0,
            stdout="ok",
            stderr="",
            timed_out=False,
            output_path=output_path,
        )


class SandboxFailsOnce:
    def __init__(self) -> None:
        self.calls = 0

    def run(self, *, input_dir: Path, output_dir: Path, code_filename: str) -> SandboxResult:
        self.calls += 1
        output_path = output_dir / "result.docx"
        if self.calls == 1:
            return SandboxResult(
                exit_code=1,
                stdout="",
                stderr="Traceback: broken",
                timed_out=False,
                output_path=output_path,
            )

        document = Document()
        document.add_heading("Spec", level=1)
        document.add_paragraph("Generated after repair")
        document.save(output_path)
        return SandboxResult(
            exit_code=0,
            stdout="ok",
            stderr="",
            timed_out=False,
            output_path=output_path,
        )


class SandboxCreatesInvalidDocxOnce:
    def __init__(self) -> None:
        self.calls = 0

    def run(self, *, input_dir: Path, output_dir: Path, code_filename: str) -> SandboxResult:
        self.calls += 1
        output_path = output_dir / "result.docx"
        document = Document()
        if self.calls == 1:
            document.add_paragraph("This document missed the required heading.")
        else:
            document.add_heading("Spec", level=1)
            document.add_paragraph("Generated after validation repair")
        document.save(output_path)
        return SandboxResult(
            exit_code=0,
            stdout="ok",
            stderr="",
            timed_out=False,
            output_path=output_path,
        )


def test_codegen_docx_renderer_uses_sandbox_result(tmp_path) -> None:
    renderer = CodegenDocxRenderer(
        Settings(artifact_storage_path=tmp_path),
        generator=FakeGenerator(),
        sandbox=FakeSandbox(),
    )

    rendered = renderer.render(
        "art_123",
        DocumentSpec(title="Spec", content_markdown="# Spec"),
    )

    document = Document(rendered.file_path)

    assert rendered.file_name == "art_123.docx"
    assert "Generated by sandbox" in [paragraph.text for paragraph in document.paragraphs]
    assert rendered.warnings == ["Codegen warning."]
    assert (tmp_path / "codegen" / "art_123" / "input" / "generated_code.py").exists()
    assert (tmp_path / "codegen" / "art_123" / "stdout.txt").read_text(encoding="utf-8") == "ok"
    assert (tmp_path / "codegen" / "art_123" / "validation_result.json").exists()


def test_codegen_docx_renderer_falls_back_when_codegen_fails(tmp_path) -> None:
    renderer = CodegenDocxRenderer(
        Settings(artifact_storage_path=tmp_path),
        generator=FailingGenerator(),
        sandbox=FakeSandbox(),
        fallback_renderer=DocxRenderer(Settings(artifact_storage_path=tmp_path)),
    )

    rendered = renderer.render(
        "art_123",
        DocumentSpec(title="Fallback", content_markdown="# Fallback\n\nBody"),
    )

    document = Document(rendered.file_path)
    paragraphs = [paragraph.text for paragraph in document.paragraphs]

    assert "Fallback" in paragraphs
    assert any("fallback renderer was used" in warning for warning in rendered.warnings)


def test_codegen_docx_renderer_repairs_after_sandbox_failure(tmp_path) -> None:
    generator = RepairingGenerator()
    renderer = CodegenDocxRenderer(
        Settings(artifact_storage_path=tmp_path, docx_codegen_repair_attempts=1),
        generator=generator,
        sandbox=SandboxFailsOnce(),
    )

    rendered = renderer.render(
        "art_123",
        DocumentSpec(title="Spec", content_markdown="# Spec\n\nBody"),
    )

    document = Document(rendered.file_path)
    paragraphs = [paragraph.text for paragraph in document.paragraphs]

    assert "Generated after repair" in paragraphs
    assert len(generator.repairs) == 1
    assert generator.repairs[0]["sandbox_result"]["exit_code"] == 1
    assert any("repair attempt 1" in warning for warning in rendered.warnings)
    assert (tmp_path / "codegen" / "art_123" / "input" / "repair_1_generated_code.py").exists()
    assert (tmp_path / "codegen" / "art_123" / "repair_1_sandbox_result.json").exists()


def test_codegen_docx_renderer_repairs_after_validation_failure(tmp_path) -> None:
    generator = RepairingGenerator()
    renderer = CodegenDocxRenderer(
        Settings(artifact_storage_path=tmp_path, docx_codegen_repair_attempts=1),
        generator=generator,
        sandbox=SandboxCreatesInvalidDocxOnce(),
    )

    rendered = renderer.render(
        "art_123",
        DocumentSpec(title="Spec", content_markdown="# Spec\n\nBody"),
    )

    document = Document(rendered.file_path)
    paragraphs = [paragraph.text for paragraph in document.paragraphs]

    assert "Generated after validation repair" in paragraphs
    assert len(generator.repairs) == 1
    assert generator.repairs[0]["validation_errors"]
    assert any("missing required heading" in error for error in generator.repairs[0]["validation_errors"])
    assert (tmp_path / "codegen" / "art_123" / "validation_result.json").exists()
    assert (tmp_path / "codegen" / "art_123" / "repair_1_validation_result.json").exists()
